name: CI

on:
  push:
    branches: [main, development, mvp/focus-cli]
  pull_request:
    branches: [main, development]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev] || pip install -e .

      - name: Lint with ruff
        run: ruff check

      - name: Run tests
        run: pytest -q

      - name: Check task execution blocks (warning only)
        run: |
          if find tasks/ -name "task-*.md" -exec grep -L "Execution Block" {} + 2>/dev/null | head -1; then
            echo "::warning::Some task files missing Execution Block"
          fi
        continue-on-error: true
